### ISSUE TITLE
无法使用添加文字的功能了，同时无法调出笔触粗细的按钮

### ISSUE THREAD

**Issue by dezerlin** [wotermelon/vue-painting#1]
虽然在dist/demo里这个功能是OK的，引用dist/vue-painting.js来用也是OK的
但是用npm start跑起来就无法使用添加文字的功能了，同时无法调出笔触粗细的按钮
用npm run build:demo, npm run build:cmpt重新生成的dist里的文件好像也有同样的问题
是因为现在用npm安装的包里有什么内容和之前的设计冲突了吗？

谢谢！

**Comment by wotermelon** [comment]
emmmm，我看下

**Comment by dezerlin** [comment]
wotermelon，你那里有复现出来吧？

**Comment by wotermelon** [comment]
无法调出笔触粗细是个问题，已解决。
添加文字功能由于konva更新的问题导致，已解决。
由于工作忙，现在才修复。
